### ISSUE TITLE
[Epic] All Samples

### ISSUE THREAD

**Issue by chenrujun** [Azure-Samples/spring-boot-application-with-azure-active-directory#12]
- [ ] Azure Active Directory
    - [ ] Servlet Applications
      - [ ] OAuth2 (OpenID)
        - [ ] Login
        - [x] client
        - [x] resource-server
        - [x] resource-server check-permission by claims in access-token
        - [x] client access resource-server
        - [x] client access multiple resource-server
        - [x] On-Behalf-of flow
        - [ ] MFA
        - [ ] Gateway
      - [ ] SAML2 
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway
      - [ ] LDAP
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway
    - [ ] Reactive Applications
      - [ ] OAuth2
        - [ ] Login
        - [ ] client
        - [ ] resource-server
        - [ ] resource-server check-permission by claims in access-token
        - [ ] client access resource-server
        - [ ] client access multiple resource-server
        - [ ] On-Behalf-of flow
        - [ ] MFA
        - [ ] Gateway
      - [ ] SAML2 
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway
      - [ ] LDAP
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway

TODO: Create a new repo named: spring-boot-application-with-azure-active-directory-b2c
 - [ ] Azure Active Directory B2C
    - [ ] Servlet Applications
      - [ ] OAuth2
        - [ ] Login
        - [ ] client
        - [ ] resource-server
        - [ ] resource-server check-permission by claims in access-token
        - [ ] client access resource-server
        - [ ] client access multiple resource-server
        - [ ] On-Behalf-of flow
        - [ ] MFA
        - [ ] Gateway
      - [ ] SAML2 
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway
      - [ ] LDAP
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway
    - [ ] Reactive Applications
      - [ ] OAuth2
        - [ ] Login
        - [ ] client
        - [ ] resource-server
        - [ ] resource-server check-permission by claims in access-token
        - [ ] client access resource-server
        - [ ] client access multiple resource-server
        - [ ] On-Behalf-of flow
        - [ ] MFA
        - [ ] Gateway
      - [ ] SAML2 
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway
      - [ ] LDAP
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway

**Comment by chenrujun** [comment]
Closing this issue, use this one instead: https://github.com/Azure/azure-sdk-for-java/issues/25817
